#!/usr/bin/env python3
"""Generate supabase/seed.sql vehicle rows from the real GTA VI vehicle
work list. Source of truth: outputs/GTA6-Fahrzeuge-Racing-Klassen-2026-09-03-v2.xlsx
(sheet 'Fahrzeuge'). Regenerate this whenever that workbook changes.

Usage: python3 scripts/generate_vehicle_seed.py > supabase/seed.sql
"""
import re
import sys
import unicodedata
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "outputs" / "GTA6-Fahrzeuge-Racing-Klassen-2026-09-03-v2.xlsx"

# Manufacturer -> logo slug, must match src/data/leaderboard.ts makeSlug and
# Visual/Logos/Car Manufacturers/web/manifest.json.
def logo_slug(make: str) -> str:
    normalized = unicodedata.normalize("NFKD", make).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", "", normalized.lower())


def slugify(*parts: str) -> str:
    text = " ".join(parts)
    normalized = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-z0-9]+", "-", normalized.lower()).strip("-")
    return slug


def sql_str(value) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    if not XLSX.exists():
        print(f"-- ERROR: source workbook not found at {XLSX}", file=sys.stderr)
        sys.exit(1)

    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb["Fahrzeuge"]
    rows = []
    skipped_unconfirmed = 0
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row, values_only=True):
        nr, klasse, hersteller, modell = row[0], row[1], row[2], row[3]
        if nr is None:
            continue
        if hersteller is None or modell is None:
            # In-game manufacturer/model not yet confirmed for this real-world
            # reference (see 'Ingame-Name bekannt' column). Never invented —
            # excluded from the seed until confirmed in the source workbook.
            skipped_unconfirmed += 1
            continue
        rows.append((int(nr), str(klasse).strip(), str(hersteller).strip(), str(modell).strip()))
    print(f"-- {skipped_unconfirmed} row(s) skipped: in-game make/model not yet confirmed in source workbook.", file=sys.stderr)

    seen_make_model = {}
    duplicates = []
    deduped_rows = []
    for nr, klasse, hersteller, modell in rows:
        key = (hersteller, modell)
        if key in seen_make_model:
            duplicates.append((nr, klasse, hersteller, modell, seen_make_model[key]))
            continue
        seen_make_model[key] = (nr, klasse)
        deduped_rows.append((nr, klasse, hersteller, modell))
    if duplicates:
        print(f"-- WARNING: {len(duplicates)} duplicate (make, model) pair(s) in the source workbook, kept only the first occurrence:", file=sys.stderr)
        for nr, klasse, hersteller, modell, first in duplicates:
            print(f"--   Nr.{nr} ({klasse}) duplicates {hersteller} {modell} already seen as Nr.{first[0]} ({first[1]}) -- check the source workbook.", file=sys.stderr)
    rows = deduped_rows

    seen_slugs = {}
    out = []
    out.append("-- Auto-generated by scripts/generate_vehicle_seed.py. Do not hand-edit.")
    out.append(f"-- Source: outputs/GTA6-Fahrzeuge-Racing-Klassen-2026-09-03-v2.xlsx ({len(rows)} vehicles).")
    out.append("")
    out.append("insert into public.tracks (track_id, name, layout_id) values")
    out.append("  ('gellhorn-international-raceway', 'Gellhorn International Raceway', 'default')")
    out.append("on conflict (track_id) do nothing;")
    out.append("")
    out.append("insert into public.vehicles (vehicle_id, source_nr, class, make, model, manufacturer_logo_slug) values")
    value_lines = []
    for nr, klasse, hersteller, modell in rows:
        base_slug = slugify(hersteller, modell)
        slug = base_slug
        n = seen_slugs.get(base_slug, 0)
        if n:
            slug = f"{base_slug}-{n+1}"
        seen_slugs[base_slug] = n + 1
        value_lines.append(
            f"  ({sql_str(slug)}, {nr}, {sql_str(klasse)}, {sql_str(hersteller)}, {sql_str(modell)}, {sql_str(logo_slug(hersteller))})"
        )
    out.append(",\n".join(value_lines) + "")
    out.append("on conflict (vehicle_id) do update set")
    out.append("  source_nr = excluded.source_nr,")
    out.append("  class = excluded.class,")
    out.append("  make = excluded.make,")
    out.append("  model = excluded.model,")
    out.append("  manufacturer_logo_slug = excluded.manufacturer_logo_slug;")
    print("\n".join(out))


if __name__ == "__main__":
    main()
