-- RS-0047 (DEC-0084): game releases + vehicle release metadata.
-- Source: Codex Zuarbeit/GTA-VI-Fahrzeug-Metadaten-9-Klassen-2026-09-30.csv, with
-- corrections: edition/pack vehicles -> base-game (edition stays in site acquisition),
-- leak-only vehicles (incl. Declasse Vamos) -> no release / no first_seen_in,
-- Ganado '70 first_seen_in = Trailer 2, Karin Contender inspiration = Toyota Tundra.

create table public.game_releases (
  release_id   text primary key,
  name         text not null,
  kind         text not null check (kind in ('base-game', 'update', 'dlc')),
  release_date date,            -- null = date not announced
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);
alter table public.game_releases enable row level security;
create policy game_releases_public_read on public.game_releases for select to public using (true);
grant select on public.game_releases to anon, authenticated;

insert into public.game_releases (release_id, name, kind, release_date, sort_order)
values ('base-game', 'Base Game', 'base-game', '2026-11-19', 0);

alter table public.vehicles
  add column release_id text references public.game_releases (release_id),
  add column first_seen_in text,
  add column real_life_inspiration text;

create index vehicles_release_id_idx on public.vehicles (release_id);

update public.vehicles v
set release_id = d.release_id, first_seen_in = d.first_seen_in, real_life_inspiration = d.real_life_inspiration
from (values
  ('albany-alpha', null, null, 'Cadillac ATS'),
  ('albany-buccaneer', 'base-game', 'Trailer 1', 'Ford Fairlane'),
  ('albany-buccaneer-custom', 'base-game', 'Trailer 1', 'Ford Fairlane'),
  ('albany-cavalcade-xl', 'base-game', 'Official screenshots', 'Cadillac Escalade-V (2023)'),
  ('albany-emperor', 'base-game', 'Official screenshots', 'Cadillac Sedan de Ville (1977–1980)'),
  ('albany-manana', 'base-game', 'Official screenshots', 'Buick LeSabre'),
  ('albany-primo', 'base-game', 'Trailer 1', 'Pontiac Bonneville (late 1980s)'),
  ('albany-v-str', 'base-game', 'Official screenshots', 'Cadillac CTS-V (third generation)'),
  ('annis-elegy-retro-custom', 'base-game', 'Trailer 1', 'Nissan Skyline GT-R R32'),
  ('annis-hellion', 'base-game', 'Trailer 1', 'Nissan Patrol Safari Y60'),
  ('benefactor-dubsta', 'base-game', 'Trailer 1', 'Mercedes-Benz G-Class'),
  ('benefactor-schafter-v12', 'base-game', 'Trailer 1', 'Brabus E V12'),
  ('benefactor-xls', 'base-game', 'An Extended Look', 'Mercedes-Benz GL-Class'),
  ('bravado-banshee', 'base-game', 'Trailer 2', 'Dodge Viper'),
  ('bravado-buffalo', 'base-game', 'Trailer 1', 'Dodge Charger'),
  ('bravado-buffalo-stx', 'base-game', 'Trailer 1', 'Dodge Charger (2015)'),
  ('bravado-dorado', 'base-game', 'Official screenshots', 'Dodge Durango (first generation)'),
  ('bravado-gauntlet-classic', 'base-game', 'Trailer 1', 'Dodge Challenger (first generation)'),
  ('bravado-gauntlet-hellfire', 'base-game', 'Trailer 1', 'Dodge Challenger SRT Demon (2018)'),
  ('buckingham-jubilee', 'base-game', 'Trailer 1', 'Rolls-Royce Cullinan'),
  ('canis-kamacho', 'base-game', 'Official screenshots', 'Jeep Crew Chief 715 concept'),
  ('canis-mesa', 'base-game', 'Official screenshots', 'Jeep Wrangler'),
  ('canis-seminole-frontier', 'base-game', 'Trailer 1', 'Jeep Cherokee (XJ)'),
  ('coil-raiden', 'base-game', 'Official screenshots', 'Tesla Model S'),
  ('declasse-granger', 'base-game', 'Trailer 2', 'Chevrolet Suburban'),
  ('declasse-granger-3600lx', 'base-game', 'Trailer 1', 'Chevrolet Suburban (2015–2020)'),
  ('declasse-impaler-80', 'base-game', 'Official screenshots', 'Chevrolet Impala (sixth generation)'),
  ('declasse-impaler-sz', 'base-game', 'Official screenshots', 'Chevrolet Impala SS (1994–1996)'),
  ('declasse-mamba-gt', 'base-game', 'Official screenshots', 'Shelby Daytona Coupe'),
  ('declasse-moonbeam', null, null, 'Chevrolet Astro (1985–1994)'),
  ('declasse-sabre-turbo', 'base-game', 'Trailer 1', 'Chevrolet Chevelle'),
  ('declasse-tornado', null, null, 'Chevrolet Bel Air'),
  ('declasse-tulip', 'base-game', 'Trailer 1', 'Chevrolet Chevelle Malibu (1972)'),
  ('declasse-tulip-m-100', 'base-game', 'Trailer 1', 'Chevrolet Malibu (fourth generation)'),
  ('declasse-vamos', null, null, 'Chevrolet Nova'),
  ('declasse-vigero-zx-convertible', 'base-game', 'Official screenshots', 'Chevrolet Camaro (sixth generation)'),
  ('dinka-blista-compact', 'base-game', 'Official screenshots', 'Honda CR-X (first generation)'),
  ('dinka-sugoi', 'base-game', 'Official screenshots', 'Honda Civic Type R FK8'),
  ('dundreary-landstalker-xl', 'base-game', 'Trailer 2', 'Lincoln Navigator (fourth generation)'),
  ('dundreary-regina', null, null, 'Chevrolet Caprice wagon'),
  ('dundreary-sirius', 'base-game', 'Official screenshots', 'Mercury Cougar (1970)'),
  ('emperor-vectre', 'base-game', 'Trailer 2', 'Lexus RC F'),
  ('enus-paragon-r', 'base-game', 'Official screenshots', 'Bentley Continental GT (third generation)'),
  ('enus-windsor', 'base-game', 'Trailer 2', 'Rolls-Royce Wraith'),
  ('fathom-fr36', 'base-game', 'An Extended Look', 'Infiniti G35 Coupé (V35)'),
  ('gallivanter-baller-ii', 'base-game', 'Official screenshots', 'Range Rover Sport'),
  ('gallivanter-baller-st-d', 'base-game', 'Official screenshots', 'Range Rover (L460)'),
  ('grotti-carbonizzare', 'base-game', 'Trailer 1', 'Aston Martin V12 Zagato'),
  ('grotti-cheetah-95', 'base-game', 'Trailer 1', 'Ferrari Testarossa'),
  ('grotti-furia', 'base-game', 'Trailer 1', 'Pininfarina Battista'),
  ('grotti-itali-rsx', 'base-game', 'An Extended Look', 'Ferrari SF90 Stradale'),
  ('imponte-df8-90', null, null, 'Pontiac G6'),
  ('imponte-phoenix', 'base-game', 'Trailer 2', 'Pontiac Firebird (second generation)'),
  ('imponte-ruiner', 'base-game', 'Trailer 1', 'Pontiac Firebird Trans Am (third generation)'),
  ('invetero-coquette', 'base-game', 'Trailer 2', 'Chevrolet Corvette C7'),
  ('invetero-coquette-d10', 'base-game', 'Trailer 1', 'Chevrolet Corvette C8'),
  ('karin-asterope-gz', 'base-game', 'Official screenshots', 'Toyota Camry (XV30)'),
  ('karin-contender', 'base-game', 'Official screenshots', 'Toyota Tundra'),
  ('karin-feroci', 'base-game', 'An Extended Look', 'Lexus GS 300 (S140)'),
  ('karin-futo', 'base-game', 'Trailer 1', 'Toyota Corolla Levin AE86'),
  ('karin-intruder', 'base-game', 'Trailer 1', 'Infiniti Q45'),
  ('karin-rebel', 'base-game', 'Official screenshots', 'Toyota Hilux'),
  ('karin-sultan', 'base-game', 'Trailer 1', 'Lexus IS (XE10)'),
  ('karin-vivanite', 'base-game', 'An Extended Look', 'Toyota Sienna (XL40)'),
  ('lampadati-novak', 'base-game', 'Official screenshots', 'Maserati Levante'),
  ('maibatsu-penumbra', 'base-game', 'Trailer 2', 'Mitsubishi Eclipse (fourth generation)'),
  ('maibatsu-penumbra-ff', 'base-game', 'An Extended Look', 'Mitsubishi Eclipse (second generation)'),
  ('mammoth-patriot-mil-spec', 'base-game', 'An Extended Look', 'Hummer H1'),
  ('obey-8f-drafter', 'base-game', 'Official screenshots', 'Audi RS5 Coupé (2018)'),
  ('obey-omnis-e-gt', 'base-game', 'Trailer 1', 'Audi e-tron GT'),
  ('obey-tailgater', 'base-game', 'Trailer 1', 'Audi A6'),
  ('obey-tailgater-s', 'base-game', 'Official screenshots', 'Audi RS3 Sedan'),
  ('ocelot-jugular', 'base-game', 'Trailer 1', 'Jaguar XE SV Project 8'),
  ('ocelot-locust', null, null, 'Lotus 3-Eleven'),
  ('pegassi-infernus-classic', 'base-game', 'An Extended Look', 'Lamborghini Diablo'),
  ('pegassi-tempesta', 'base-game', 'Trailer 2', 'Lamborghini Huracán'),
  ('pegassi-toros', 'base-game', 'Official screenshots', 'Lamborghini Urus'),
  ('pegassi-zorrusso', 'base-game', 'Trailer 1', 'Italdesign Zerouno'),
  ('pfister-astron', 'base-game', 'Trailer 2', 'Porsche Macan'),
  ('pfister-comet-retro-custom', 'base-game', 'Trailer 1', 'Porsche 911 Turbo (930) with RWB styling'),
  ('pfister-comet-s2-cabrio', 'base-game', 'Trailer 1', 'Porsche 911 Turbo S Cabriolet (992)'),
  ('pfister-growler', 'base-game', 'Trailer 2', 'Porsche 718 Cayman'),
  ('pfister-neon', 'base-game', 'An Extended Look', 'Porsche Taycan'),
  ('schyster-deviant', 'base-game', 'Official screenshots', 'AMC Javelin (1972)'),
  ('schyster-pmp-700', 'base-game', 'Trailer 1', 'Chrysler 300 (LD)'),
  ('truffade-thrax', null, null, 'Bugatti Divo'),
  ('ubermacht-cypher', 'base-game', 'Trailer 1', 'BMW M2 (F87)'),
  ('ubermacht-sentinel-classic', 'base-game', 'An Extended Look', 'BMW M3 (E30)'),
  ('ubermacht-sentinel-classic-cabrio', 'base-game', 'GTA VI promotional website', 'BMW 3 Series Cabriolet (E30)'),
  ('ubermacht-sentinel-xs', 'base-game', 'Trailer 2', 'BMW M3 (E92)'),
  ('ubermacht-zion', 'base-game', 'Official screenshots', 'BMW M6 (E63)'),
  ('ubermacht-zion-cabrio', 'base-game', 'An Extended Look', 'BMW M6 Convertible (E64)'),
  ('vapid-aleutian', 'base-game', 'Trailer 2', 'Ford Expedition (U553)'),
  ('vapid-caracara-4x4', 'base-game', 'Trailer 2', 'Ford F-150 Raptor (second generation)'),
  ('vapid-chino', 'base-game', 'Trailer 1', 'Lincoln Continental (1965)'),
  ('vapid-dominator', 'base-game', 'Trailer 1', 'Ford Mustang (fifth generation)'),
  ('vapid-dominator-67-buggy', 'base-game', 'Ultimate Edition reveal', 'Ford Mustang (first generation)'),
  ('vapid-dominator-asp', 'base-game', 'Trailer 1', 'Ford Mustang SVT Cobra R (2000)'),
  ('vapid-dominator-gt', 'base-game', 'Official screenshots', 'Ford Mustang Convertible (2018–2023)'),
  ('vapid-dominator-gtx', 'base-game', 'Trailer 1', 'Ford Mustang (sixth generation)'),
  ('vapid-ganado-70', 'base-game', 'Trailer 2', 'Ford Ranchero (1970)'),
  ('vapid-montagne', 'base-game', 'Trailer 2', 'Ford Explorer (sixth generation)'),
  ('vapid-riata-classic', 'base-game', 'Official screenshots', 'Ford Bronco (first generation)'),
  ('vapid-slamvan', 'base-game', 'Trailer 1', 'Ford F-Series (1953–1956)'),
  ('vapid-stanier', 'base-game', 'Trailer 1', 'Ford Crown Victoria'),
  ('vapid-stanier-55', 'base-game', 'Trailer 1', 'Ford Fairlane Club Sedan (1956)'),
  ('vulcar-ingot', null, null, 'Volkswagen Passat wagon'),
  ('zirconium-stratum', 'base-game', 'Trailer 1', 'Honda Accord wagon')
) as d (vehicle_id, release_id, first_seen_in, real_life_inspiration)
where v.vehicle_id = d.vehicle_id;
